### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by eosclassicteam** [sponnet/locals-faucetserver#10]
```
connecting to EOSC node:  https://test-node.eos-classic.io
Wallet initted addr=25f82d2f87dfab2bc40f1acdcd545ea085a396a4
faucet listening on port  3001
last donation: 1531765593297
gasprice is  10000000000
Transferring  100000000000000000000 wei from 0x25f82d2f87dfab2bc40f1acdcd545ea085a396a4 to 0xdecaf9cd2367cdbb726e904cd6397edfcae6068d
{ from: '0x25f82d2f87dfab2bc40f1acdcd545ea085a396a4',
  to: '0xdecaf9cd2367cdbb726e904cd6397edfcae6068d',
  value: 100000000000000000000,
  gas: 21000,
  gasPrice: 10000000000 }
buffer.js:202
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at new Buffer (buffer.js:158:17)
    at Object.nacl.util.encodeBase64 (/home/ubuntu/eosc-faucet/node_modules/tweetnacl/nacl-fast.js:2176:13)
    at nacl_encodeHex (/home/ubuntu/eosc-faucet/node_modules/eth-lightwallet/lib/keystore.js:50:29)
    at Function.KeyStore._decryptKey (/home/ubuntu/eosc-faucet/node_modules/eth-lightwallet/lib/keystore.js:146:10)
    at KeyStore.exportPrivateKey (/home/ubuntu/eosc-faucet/node_modules/eth-lightwallet/lib/keystore.js:373:26)
    at Object.signTx (/home/ubuntu/eosc-faucet/node_modules/eth-lightwallet/lib/signing.js:16:26)
    at /home/ubuntu/eosc-faucet/node_modules/eth-lightwallet/lib/keystore.js:520:30
    at cb (/home/ubuntu/eosc-faucet/node_modules/eth-lightwallet/lib/keystore.js:457:5)
    at /home/ubuntu/eosc-faucet/node_modules/scrypt-async/scrypt-async.js:518:13
```

Typeerror appears when I tried to execute any transactions

Any suggestions??

**Comment by sponnet** [comment]
I don't know what you're trying to achieve here ?

**Comment by sponnet** [comment]
In the current version committed today on master - the password of the wallet used should be specified from the config file.
In the older version the password is defined twice in the code - resulting in the above error... ( search in the file to find the 2 occurrences and change in these 2 places) OR upgrade to the latest master version.
