### ISSUE TITLE
Wallet issues starting faucetserver

### ISSUE THREAD

**Issue by mayhem** [sponnet/locals-faucetserver#49]
I'm trying to install this code (using Docker), but it keeps failing with this error:

```
faucet_1  | 2022/03/21 23:14:32 Connected to tcp://faucetserver_geth_1:8545
faucet_1  | connecting to http://faucetserver_geth_1:8545
faucet_1  | /faucetserver/locals-faucetserver/node_modules/@ethersproject/bytes/lib/index.js:9
faucet_1  |     return !!(value.toHexString);
faucet_1  |                     ^
faucet_1  | 
faucet_1  | TypeError: Cannot read properties of undefined (reading 'toHexString')
faucet_1  |     at isHexable (/faucetserver/locals-faucetserver/node_modules/@ethersproject/bytes/lib/index.js:9:21)
faucet_1  |     at hexlify (/faucetserver/locals-faucetserver/node_modules/@ethersproject/bytes/lib/index.js:175:9)
faucet_1  |     at new SigningKey (/faucetserver/locals-faucetserver/node_modules/@ethersproject/signing-key/lib/index.js:20:82)
faucet_1  |     at new Wallet (/faucetserver/locals-faucetserver/node_modules/@ethersproject/wallet/lib/index.js:123:36)
faucet_1  |     at Object.<anonymous> (/faucetserver/locals-faucetserver/index.js:15:14)
faucet_1  |     at Module._compile (node:internal/modules/cjs/loader:1099:14)
faucet_1  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
faucet_1  |     at Module.load (node:internal/modules/cjs/loader:975:32)
faucet_1  |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
faucet_1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
faucet_1  | 
faucet_1  | Node.js v17.7.2
faucet_1  | 2022/03/21 23:14:33 Command exited with error: exit status 1
faucetserver_faucet_1 exited with code 1
```
I've tried using the mkwallet.js and I've tried installing a JSON wallet that I generated on the web, but no luck. mkwallet.js was giving me issues, because eth-lightwallet has changed how it should be invoked:

https://www.npmjs.com/package/eth-lightwallet

Currently the faucet uses the old style, but I haven't been able to upgrade the code to use the new style (since I am quite unfamiliar with Ethereum in general -- I'm helping a friend setup a server) -- it keeps failing in the same way as above. To me it looks like the wallet isn't formatted correctly for the faucet to read it.

Any tips on how to proceed with this?

Thanks!

**Comment by alxnode** [comment]
facing the same problem and can fix for 3 day
